apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: microbe-volume-claim
  namespace: microbe-hl-prod
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  volumeName: microbe-vol-1
