---
title: "Datasets"
---

All MICROBE samples are registered in [BioSamples](https://ebi.ac.uk/biosamples),
which has [its own documentation](https://www.ebi.ac.uk/biosamples/docs).

Most analyses of the samples are stored in further appropriate supporting databases, 
with a small number hosted directly in the MICROBE data portal.

## ENA Samples / BioSamples
BioSamples are the "source of truth" for samples created by the project.
Some samples are also present in ENA (with the same primary accession / identifier), if those samples pertain to nucleotide read data.

An ENA Sample is part of the [ENA Metadata Model](https://ena-docs.readthedocs.io/en/latest/submit/general-guide/metadata.html#metadata-model).

> A sample contains information about the sequenced source material. Samples are associated with checklists, which define the fields used to annotate the samples.

ENA has [extensive documentation](https://www.ebi.ac.uk/ena/browser/guides).

## ENA Checklist Metadata
An [ENA Checklist](https://ena-docs.readthedocs.io/en/latest/retrieval/ena-project.html?highlight=checklist#sample-checklists) 
is a set of metadata (some mandatory) for a given sample type.

## BioSamples Metadata
TODO

There is a [BioSamples online training course](https://www.ebi.ac.uk/training/online/courses/biosamples-quick-tour/what-is-biosamples)
to learn more.

## MGnify: Metagenomics
Metagenomic-derived analyses are available for some MICROBE samples.

These datasets and analysis features are hosted by [MGnify](https://ebi.ac.uk/metagenomics), which also has [extensive documentation](https://docs.mgnify.org/).

> MGnify is a freely available hub for the analysis and exploration of metagenomic, metatranscriptomic, amplicon and assembly data.

## Summary analyses
Summary analyses are higher level analyses of a Sample or collection of Samples; 
written documents serving as short analysis summaries.

These summaries are hosted directly by the MICROBE data portal.

The documents are written by MICROBE partners and moderated by the MICROBE consortium,
but are not peer-reviewed research articles.

Each analysis summary is linked to one or more Samples that were included in the analysis or are relevant to it.