# Generated by Django 6.0.4 on 2026-06-08 16:09

import django.db.models.deletion
import martor.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SynComConstituent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organism", models.CharField(max_length=256)),
                ("accession", models.CharField(max_length=256)),
                ("attributes", models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "accession",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "experiment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SynComs", "SynComs"),
                            ("Cryopreservation", "Cryopreservation"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Soil", "Soil"),
                            ("Seed", "Seed"),
                            ("Marine", "Marine"),
                            ("Human", "Human"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Use case/biome",
                    ),
                ),
                (
                    "sample_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("metagenomic_assembly", "metagenomic_assembly"),
                            ("metagenomic_amplicon", "metagenomic_amplicon"),
                            ("metabolomic", "metabolomic"),
                            ("metabolomic_targeted", "metabolomic_targeted"),
                            ("histological", "histological"),
                            ("host_genomic", "host_genomic"),
                            ("transcriptomic", "transcriptomic"),
                            ("metatranscriptomic", "metatranscriptomic"),
                            ("iodine", "iodine"),
                            ("fatty_acids", "fatty_acids"),
                            ("heavy_metals", "heavy_metals"),
                            ("inflammatory_markers", "inflammatory_markers"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "metabolights_study",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("biologs", models.JSONField(blank=True, default=list, null=True)),
                ("attributes", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "preservation_method",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "derived_from",
                    models.ManyToManyField(
                        related_name="derived_samples", to="microbe.sample"
                    ),
                ),
                (
                    "syncom_constituents",
                    models.ManyToManyField(
                        related_name="syncoms", to="microbe.syncomconstituent"
                    ),
                ),
            ],
            options={
                "ordering": ("accession",),
            },
        ),
        migrations.CreateModel(
            name="AnalysisSummary",
            fields=[
                ("created", models.DateTimeField(auto_created=True, auto_now_add=True)),
                (
                    "slug",
                    models.SlugField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "content",
                    martor.models.MartorField(
                        help_text="Markdown document describing an analysis of one or more catalogues/samples"
                    ),
                ),
                ("author", models.CharField(max_length=200)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "samples",
                    models.ManyToManyField(
                        blank=True,
                        related_name="analysis_summaries",
                        to="microbe.sample",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "analysis summaries",
                "permissions": [
                    ("publish_annotation", "Can publish an analysis summary")
                ],
            },
        ),
        migrations.CreateModel(
            name="SampleMetadataMarker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("iri", models.CharField(blank=True, max_length=100, null=True)),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "ordering": ("type",),
                "indexes": [
                    models.Index(fields=["name"], name="microbe_sam_name_a5fa76_idx")
                ],
                "unique_together": {("name", "type")},
            },
        ),
        migrations.CreateModel(
            name="SampleStructuredDatum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("ena", "ena"), ("biosamples", "biosamples")],
                        max_length=15,
                    ),
                ),
                ("measurement", models.CharField(max_length=300)),
                ("units", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "partner_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "partner_iri",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "marker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="microbe.samplemetadatamarker",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structured_metadata",
                        to="microbe.sample",
                    ),
                ),
            ],
            options={
                "ordering": ("marker__type", "marker__name", "id"),
            },
        ),
    ]
