# Generated by Django 6.0.4 on 2026-04-29 10:53

import django.db.models.deletion
import martor.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Environment",
            fields=[
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Soil", "Soil"),
                            ("Seed", "Seed"),
                            ("Marine", "Marine"),
                        ],
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="GenomeCatalogue",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=100)),
                ("biome", models.CharField(max_length=200)),
                ("related_mag_catalogue_id", models.CharField(max_length=100)),
                (
                    "use_case",
                    models.CharField(
                        choices=[
                            ("SynComs", "SynComs"),
                            ("Cryopreservation", "Cryopreservation"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UseCase",
            fields=[
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("SynComs", "SynComs"),
                            ("Cryopreservation", "Cryopreservation"),
                        ],
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Genome",
            fields=[
                (
                    "accession",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("cluster_representative", models.CharField(max_length=15)),
                ("taxonomy", models.CharField(max_length=200)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("annotations", models.JSONField(blank=True, default=dict)),
                (
                    "catalogue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="genomes",
                        to="microbe.genomecatalogue",
                    ),
                ),
            ],
            options={
                "ordering": ("accession",),
            },
        ),
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "accession",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "sample_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("metagenomic_assembly", "metagenomic_assembly"),
                            ("metagenomic_amplicon", "metagenomic_amplicon"),
                            ("metabolomic", "metabolomic"),
                            ("metabolomic_targeted", "metabolomic_targeted"),
                            ("histological", "histological"),
                            ("host_genomic", "host_genomic"),
                            ("transcriptomic", "transcriptomic"),
                            ("metatranscriptomic", "metatranscriptomic"),
                            ("iodine", "iodine"),
                            ("fatty_acids", "fatty_acids"),
                            ("heavy_metals", "heavy_metals"),
                            ("inflammatory_markers", "inflammatory_markers"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "metabolights_study",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="microbe.environment",
                    ),
                ),
            ],
            options={
                "ordering": ("accession",),
            },
        ),
        migrations.CreateModel(
            name="GenomeSampleContainment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("containment", models.FloatField(default=0)),
                (
                    "genome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples_containing",
                        to="microbe.genome",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="genomes_contained",
                        to="microbe.sample",
                    ),
                ),
            ],
            options={
                "ordering": ("genome", "-containment"),
            },
        ),
        migrations.CreateModel(
            name="SampleMetadataMarker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("iri", models.CharField(blank=True, max_length=100, null=True)),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "ordering": ("type",),
                "indexes": [
                    models.Index(fields=["name"], name="microbe_sam_name_a5fa76_idx")
                ],
                "unique_together": {("name", "type")},
            },
        ),
        migrations.CreateModel(
            name="SampleStructuredDatum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("ena", "ena"), ("biosamples", "biosamples")],
                        max_length=15,
                    ),
                ),
                ("measurement", models.CharField(max_length=300)),
                ("units", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "partner_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "partner_iri",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "marker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="microbe.samplemetadatamarker",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structured_metadata",
                        to="microbe.sample",
                    ),
                ),
            ],
            options={
                "ordering": ("marker__type", "marker__name", "id"),
            },
        ),
        migrations.AddField(
            model_name="environment",
            name="use_case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="environments",
                to="microbe.usecase",
            ),
        ),
        migrations.CreateModel(
            name="ViralCatalogue",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=100)),
                ("biome", models.CharField(max_length=200)),
                (
                    "use_case",
                    models.CharField(
                        choices=[
                            ("SynComs", "SynComs"),
                            ("Cryopreservation", "Cryopreservation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "related_genome_catalogue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="viral_catalogues",
                        to="microbe.genomecatalogue",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnalysisSummary",
            fields=[
                ("created", models.DateTimeField(auto_created=True, auto_now_add=True)),
                (
                    "slug",
                    models.SlugField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "content",
                    martor.models.MartorField(
                        help_text="Markdown document describing an analysis of one or more catalogues/samples"
                    ),
                ),
                ("author", models.CharField(max_length=200)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "genome_catalogues",
                    models.ManyToManyField(
                        blank=True,
                        related_name="analysis_summaries",
                        to="microbe.genomecatalogue",
                    ),
                ),
                (
                    "samples",
                    models.ManyToManyField(
                        blank=True,
                        related_name="analysis_summaries",
                        to="microbe.sample",
                    ),
                ),
                (
                    "viral_catalogues",
                    models.ManyToManyField(
                        blank=True,
                        related_name="analysis_summaries",
                        to="microbe.viralcatalogue",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "analysis summaries",
                "permissions": [
                    ("publish_annotation", "Can publish an analysis summary")
                ],
            },
        ),
        migrations.CreateModel(
            name="ViralFragment",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contig_id",
                    models.CharField(max_length=100, verbose_name="Contig ID"),
                ),
                ("mgnify_analysis_accession", models.CharField(max_length=12)),
                ("start_within_contig", models.IntegerField()),
                ("end_within_contig", models.IntegerField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "viral_type",
                    models.CharField(
                        choices=[
                            ("viral_sequence", "viral_sequence"),
                            ("prophage", "prophage"),
                        ],
                        max_length=15,
                    ),
                ),
                ("taxonomy", models.CharField(blank=True, max_length=100, null=True)),
                ("gff", models.TextField(blank=True, default="")),
                (
                    "catalogue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viral_fragments",
                        to="microbe.viralcatalogue",
                    ),
                ),
                (
                    "cluster_representative",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cluster_members",
                        to="microbe.viralfragment",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
