# Generated by Django 6.0.4 on 2026-05-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("microbe", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="environment",
            name="use_case",
        ),
        migrations.AlterField(
            model_name="sample",
            name="environment",
            field=models.CharField(
                blank=True,
                choices=[("Soil", "Soil"), ("Seed", "Seed"), ("Marine", "Marine")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="use_case",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SynComs", "SynComs"),
                    ("Cryopreservation", "Cryopreservation"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="UseCase",
        ),
        migrations.DeleteModel(
            name="Environment",
        ),
    ]
