# Generated by Django 6.0.4 on 2026-05-06 12:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "microbe",
            "0002_remove_environment_use_case_alter_sample_environment_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genomesamplecontainment",
            name="genome",
        ),
        migrations.RemoveField(
            model_name="viralcatalogue",
            name="related_genome_catalogue",
        ),
        migrations.RemoveField(
            model_name="analysissummary",
            name="genome_catalogues",
        ),
        migrations.RemoveField(
            model_name="genomesamplecontainment",
            name="sample",
        ),
        migrations.RemoveField(
            model_name="analysissummary",
            name="viral_catalogues",
        ),
        migrations.RemoveField(
            model_name="viralfragment",
            name="catalogue",
        ),
        migrations.RemoveField(
            model_name="viralfragment",
            name="cluster_representative",
        ),
        migrations.DeleteModel(
            name="Genome",
        ),
        migrations.DeleteModel(
            name="GenomeCatalogue",
        ),
        migrations.DeleteModel(
            name="GenomeSampleContainment",
        ),
        migrations.DeleteModel(
            name="ViralCatalogue",
        ),
        migrations.DeleteModel(
            name="ViralFragment",
        ),
    ]
