# Generated by Django 6.0.4 on 2026-05-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("microbe", "0003_remove_genomesamplecontainment_genome_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SynComConstituent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organism", models.CharField(max_length=256)),
                ("accession", models.CharField(max_length=256)),
                ("attributes", models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="sample",
            name="attributes",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="sample",
            name="syncom_constituents",
            field=models.ManyToManyField(
                related_name="syncoms", to="microbe.syncomconstituent"
            ),
        ),
    ]
