# Generated by Django 6.0.4 on 2026-05-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("microbe", "0004_syncomconstituent_sample_attributes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="derived_from",
            field=models.ManyToManyField(
                related_name="derived_samples", to="microbe.sample"
            ),
        ),
    ]
