# Generated by Django 6.0.4 on 2026-05-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("microbe", "0005_sample_derived_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="preservation_method",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
