# Generated by Django 6.0.4 on 2026-06-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("microbe", "0006_sample_preservation_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="environment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Soil", "Soil"),
                    ("Seed", "Seed"),
                    ("Marine", "Marine"),
                    ("Human", "Human"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
