# Generated by Django 6.0.4 on 2026-06-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("microbe", "0007_alter_sample_environment"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="biologs",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="sample",
            name="environment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Soil", "Soil"),
                    ("Seed", "Seed"),
                    ("Marine", "Marine"),
                    ("Human", "Human"),
                ],
                max_length=10,
                null=True,
                verbose_name="Biome/environment",
            ),
        ),
    ]
