# Generated by Django 4.0.6 on 2022-08-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("microbe", "0015_alter_samplestructureddatum_measurement"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="has_metabolomics",
            field=models.BooleanField(default=False),
        ),
    ]
